<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="5" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-21T20:59:32 MSK" name="Surefire suite" finished-at="2024-11-21T20:59:32 MSK" duration-ms="117">
    <groups>
    </groups>
    <test started-at="2024-11-21T20:59:32 MSK" name="Surefire test" finished-at="2024-11-21T20:59:32 MSK" duration-ms="117">
      <class name="ru.mai.lessons.rpks.impl.LogAnalyzerTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:ru.mai.lessons.rpks.impl.LogAnalyzerTest@4567f35d]" started-at="2024-11-21T20:59:32 MSK" name="setUp" finished-at="2024-11-21T20:59:32 MSK" duration-ms="16" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testNegativeWrongFilename(java.lang.String)[pri:0, instance:ru.mai.lessons.rpks.impl.LogAnalyzerTest@4567f35d]" started-at="2024-11-21T20:59:32 MSK" name="testNegativeWrongFilename" description="Проверяем реакцию сервиса на ошибку при работе с файлом" data-provider="wrongFilenameCases" finished-at="2024-11-21T20:59:32 MSK" duration-ms="3" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <exception class="ru.mai.lessons.rpks.exception.WrongFilenameException">
            <message>
              <![CDATA[File path cannot be null or empty!]]>
            </message>
            <full-stacktrace>
              <![CDATA[ru.mai.lessons.rpks.exception.WrongFilenameException: File path cannot be null or empty!
at ru.mai.lessons.rpks.impl.LogAnalyzer.getPath(LogAnalyzer.java:75)
at ru.mai.lessons.rpks.impl.LogAnalyzer.analyze(LogAnalyzer.java:21)
at ru.mai.lessons.rpks.impl.LogAnalyzerTest.testNegativeWrongFilename(LogAnalyzerTest.java:77)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:155)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:102)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:91)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:137)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- ru.mai.lessons.rpks.exception.WrongFilenameException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNegativeWrongFilename -->
        <test-method signature="testNegativeWrongFilename(java.lang.String)[pri:0, instance:ru.mai.lessons.rpks.impl.LogAnalyzerTest@4567f35d]" started-at="2024-11-21T20:59:32 MSK" name="testNegativeWrongFilename" description="Проверяем реакцию сервиса на ошибку при работе с файлом" data-provider="wrongFilenameCases" finished-at="2024-11-21T20:59:32 MSK" duration-ms="2" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[unknown_file.txt]]>
              </value>
            </param>
          </params>
          <exception class="ru.mai.lessons.rpks.exception.WrongFilenameException">
            <message>
              <![CDATA[File path does not exist or is not a regular file!]]>
            </message>
            <full-stacktrace>
              <![CDATA[ru.mai.lessons.rpks.exception.WrongFilenameException: File path does not exist or is not a regular file!
at ru.mai.lessons.rpks.impl.LogAnalyzer.getPath(LogAnalyzer.java:83)
at ru.mai.lessons.rpks.impl.LogAnalyzer.analyze(LogAnalyzer.java:21)
at ru.mai.lessons.rpks.impl.LogAnalyzerTest.testNegativeWrongFilename(LogAnalyzerTest.java:77)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:155)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:102)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:91)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:137)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- ru.mai.lessons.rpks.exception.WrongFilenameException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNegativeWrongFilename -->
        <test-method signature="testPositiveAnalyze(java.lang.String,java.util.List)[pri:0, instance:ru.mai.lessons.rpks.impl.LogAnalyzerTest@4567f35d]" started-at="2024-11-21T20:59:32 MSK" name="testPositiveAnalyze" description="Проверяем границы отклонения от медианы" data-provider="validDeviationCases" finished-at="2024-11-21T20:59:32 MSK" duration-ms="22" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[3 sec]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[2, 6, 8, 11, 14]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPositiveAnalyze -->
        <test-method signature="testPositiveAnalyze(java.lang.String,java.util.List)[pri:0, instance:ru.mai.lessons.rpks.impl.LogAnalyzerTest@4567f35d]" started-at="2024-11-21T20:59:32 MSK" name="testPositiveAnalyze" description="Проверяем границы отклонения от медианы" data-provider="validDeviationCases" finished-at="2024-11-21T20:59:32 MSK" duration-ms="8" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[1 min]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[14]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPositiveAnalyze -->
        <test-method signature="testPositiveAnalyzeAnomalyForAbsentDeviationParameter()[pri:0, instance:ru.mai.lessons.rpks.impl.LogAnalyzerTest@4567f35d]" started-at="2024-11-21T20:59:32 MSK" name="testPositiveAnalyzeAnomalyForAbsentDeviationParameter" description="Проверяем, что при отсутствии параметра отклонения сервис должен самостоятельно выявить аномальные запросы" finished-at="2024-11-21T20:59:32 MSK" duration-ms="8" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPositiveAnalyzeAnomalyForAbsentDeviationParameter -->
      </class> <!-- ru.mai.lessons.rpks.impl.LogAnalyzerTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
